Repository alexander-sidorov/tms-qap05, pull requests merged in 2022-01, with the labels that each got.

#110 Sasha Yaroshevich - Lesson 05
  hw/sasha_yaroshevich/home_5_1.py
  hw/sasha_yaroshevich/test_home5.py
Labels: great success 🤟🏻

#131 Andrei Bondar - Lesson 05hw
  hw/andrei_bondar/bondar5hw.py
  hw/andrei_bondar/test_bondar5hw.py
Labels: great success 🤟🏻, deadline

#130 Siarhei Apanel - Lesson 06 HW
  hw/_qa/maria_saganovich/__init__.py
  hw/_qa/maria_saganovich/test_siarhei_func11_new_set_hw6.py
  hw/_qa/maria_saganovich/test_siarhei_html_str_hw6.py
  hw/_qa/maria_saganovich/test_siarhei_repeat_hw6.py
  hw/siarhei_apanel/Test_APANEL.py
  hw/siarhei_apanel/refakt.py
  hw/siarhei_apanel/test.py
  hw/siarhei_apanel/test_HW2.py
  hw/siarhei_apanel/test_hw.py
  hw/siarhei_apanel/test_lesson3.py
Labels: 🤟🏻 great success, 🍻 collab, 10

#117 Andrey Yelin - Lesson 05hw
  hw/andrey_yelin/Lesson_05/__init__.py
  hw/andrey_yelin/Lesson_05/test_lesson05.py
  hw/andrey_yelin/Lesson_05/test_yelin_lesson05hw.py
  hw/andrey_yelin/Lesson_05/yelin_lesson05.py
  hw/andrey_yelin/Lesson_05/yelin_lesson05hw.py
  hw/andrey_yelin/lesson_02/__init__.py
  hw/andrey_yelin/lesson_02/lesson2.py
  hw/andrey_yelin/lesson_02/test_lesson2.py
  hw/andrey_yelin/lesson_03/__init__.py
  hw/andrey_yelin/lesson_03/test_yelin.py
  hw/andrey_yelin/lesson_04/__init__.py
  hw/andrey_yelin/lesson_04/functions_l04.py
  hw/andrey_yelin/lesson_04/test_lesson04.py
  hw/andrey_yelin/test_lesson04.py
  hw/andrey_yelin/test_lesson2.py
Labels: ⌛️ deadline, 9

#149 Siarhei Apanel - Lesson 10 HW
  hw/_qa/hw06/task_01_test.py
  hw/_qa/hw06/task_02_test.py
  hw/_qa/hw06/task_03_test.py
  hw/_qa/hw06/task_04_test.py
  hw/_qa/hw06/task_05_test.py
  hw/_qa/hw06/task_06_test.py
  hw/_qa/hw06/task_07_test.py
  hw/_qa/hw06/task_08_test.py
  hw/_qa/hw06/task_09_test.py
  hw/_qa/hw06/task_10_test.py
  hw/_qa/hw06/task_11_test.py
  hw/_qa/hw06/task_12_test.py
  hw/_qa/hw10/task_01_test.py
  hw/_qa/hw10/task_02_test.py
  hw/_qa/hw10/task_03_test.py
  hw/_qa/hw10/task_04_test.py
  hw/_qa/hw10/task_05_test.py
  hw/_qa/maria_saganovich/test_siarhei_repeat_hw6.py
  hw/siarhei_apanel/class10hw.py
  hw/siarhei_apanel/decorator07.py
  hw/siarhei_apanel/refakt.py
  hw/siarhei_apanel/test_hw.py
Labels: 10

#128 Vadim Maletski - Lesson 10 HW
  hw/_qa/alexander_sidorov/vadim_maletski/__init__.py
  hw/_qa/alexander_sidorov/vadim_maletski/hw06/__init__.py
  hw/_qa/alexander_sidorov/vadim_maletski/hw06/common.py
  hw/_qa/alexander_sidorov/vadim_maletski/hw06/level_01_test.py
  hw/_qa/alexander_sidorov/vadim_maletski/hw06/level_04_test.py
  hw/_qa/alexander_sidorov/vadim_maletski/hw06/level_05_test.py
  hw/_qa/alexander_sidorov/vadim_maletski/hw06/level_06_test.py
  hw/_qa/alexander_sidorov/vadim_maletski/hw06/level_08_test.py
  hw/_qa/alexander_sidorov/vadim_maletski/hw06/level_10_test.py
  hw/_qa/hw06/task_01_test.py
  hw/_qa/hw06/task_02_test.py
  hw/_qa/hw06/task_03_test.py
  hw/_qa/hw06/task_04_test.py
  hw/_qa/hw06/task_05_test.py
  hw/_qa/hw06/task_06_test.py
  hw/_qa/hw06/task_07_test.py
  hw/_qa/hw06/task_08_test.py
  hw/_qa/hw06/task_09_test.py
  hw/_qa/hw06/task_10_test.py
  hw/_qa/hw06/task_11_test.py
  hw/_qa/hw06/task_12_test.py
  hw/_qa/hw10/task_01_test.py
  hw/_qa/hw10/task_02_test.py
  hw/_qa/hw10/task_03_test.py
  hw/_qa/hw10/task_04_test.py
  hw/_qa/hw10/task_05_test.py
  hw/vadim_maletski/func6.py
  hw/vadim_maletski/test_lesson6hw.py
Labels: 10
